name: "Build popup"

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      name: Build popup
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: "Install"
          run: npm ci
        - name: "Build"
          run: npm run build
          